    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          - name: Install valgrind
            run: sudo apt-get update; sudo apt-get install valgrind
          - uses: actions/checkout@v2
          - uses: education/autograding@v1
